### PR TITLE
Exhaustive password search and restart point

### LINKED ISSUE #34: Exhaustive password search
Hi,

I tried to recover a password from a key using the "-r 15 ?a" option, so I was expecting to only have a password with letters and numbers but the found password looks like to have strange characters:

<pre>
as bytes: ****  b5 ab 10 d2  ******
as text: *****  ���   ****
</pre>

Any idea what could be the problem?
Thanks!

### LINKED ISSUE #35: Resuming a cancelled password recovery ?
If one cancels the recovery, bkcrack now starts from the beginning.  It would be nice if recovery could be resumed...

### PR DESCRIPTION
**Pull request by kimci86**
- [x] Implement exhaustive search (resolves #34)
- [x] Ability to restart search after a non-exhaustive search or SIGINT (resolves #35)
  + [ ] Make it more precise (the starting point is coarse for now)
- [x] Print progress less often to improve performance
- [ ] Clean up implementation, profile and optimize
- [ ] Update documentation, readme, tutorial

### CODE REVIEW

**Comment by kimci86** [comment]
@geofjamg Could you try this version?

**Comment by cxzstuff** [comment]
Tried, took now 9 hours, before 8½ . Found it and continued. At 1452 instead of 1455/3844 like before. Output a bit messy as color codes didn't work on windows.
Old output:
https://forum.xda-developers.com/t/file-encrypted-how-can-i-open-it-help.4194779/post-85091353

**Comment by kimci86** [comment]
Thank you @cxzstuff for your feedback.

> Output a bit messy

I just added a workaround to have a cleaner output. I should also add a protection not to print progress and a password at the same time.

> Found it and continued. At 1452 instead of 1455/3844 like before.

The exact order in which passwords are tested can vary a little so this is normal.

> That starting point option would help a lot

I agree! I am working on it. Should be ready by the end of next week at the latest.

**Comment by kimci86** [comment]
With the last change, you can restart a password recovery stopped either because a password was found and exhaustive mode was disabled or because the program was stopped by the user (by pressing Ctrl + C or Ctrl + Shift + C). The starting point is printed before exiting.
I need to make it more precise and clean up the implementation but it can already be used to save time.

**Comment by cxzstuff** [comment]
You're quick. Works quite nicely.
bkcrack -k 6eda3a27 2edfbde4 237a1e01 -r 20 ?a -e -s 16840
gives the password right away.
If copied as in powershell/cmd window it's: "NS1kxZf8uLDAå╬"
Instead of of the right one: "NS1kxZf8uLDA†Î "
So outputting it/log into a text file could be a good enhancement.

**Comment by kimci86** [comment]
This was too old, I started over.

**Pull request closed without merging**
